apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: react-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-front
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
        - name: react-front
          image: sadilegend/todo-front:latest
          ports:
            - containerPort: 3000