apiVersion: v1
kind: Service
metadata:
  name: react-todo-svc
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: react-front
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32200
